// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiroxxxbqkosaravfsub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpcm94eHhicWtvc2FyYXZmc3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODI3MTUsImV4cCI6MjA2Mzk1ODcxNX0.GzcGJtmAFA7YbBc8DMVcuypaQjWuX9xjMzNQ_Fzt_UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);